name: trisense-webapp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyh0d26453_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.14.0=h3fc5862_101_cp314
  - python_abi=3.14=1_cp314
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - click==8.3.0
      - fastapi==0.121.0
      - h11==0.16.0
      - idna==3.11
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
prefix: /home/matevz/miniconda3/envs/trisense-webapp
