version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: .docker/Dockerfile.webapp
    container_name: fastapi-webapp
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=db.sqlite3
